Allow underscores in environment variable names
supercollider/language-supercollider pull request #3
Opened 2017-06-30 14:22 UTC by cechandler

Small addition to allow environment variables to contain underscore characters

2017-06-30 16:04 UTC, mossheim requested changes

2017-06-30 16:04 UTC, brianlheim commented on grammars/supercollider.cson
> +    'match': '\\~[a-zA-Z0-9_]+'
thanks! this is close, but not correct. `~_` isn't a valid environment variable name, nor is `~_a`. i think it should be `\\~[a-zA-Z0-9][a-zA-Z0-9_]*` then, right? (not 100% sure this notation works like the regex dialect i'm familiar with). the Supercollider IDE highlights `~_a`, i think that ought to be emended

2017-06-30 16:45 UTC, telephon commented on grammars/supercollider.cson
> +    'match': '\\~[a-zA-Z0-9_]+'
also something like `~900` isn't valid. So maybe something like

`\\~[a-zA-Z][a-zA-Z0-9_]*`
?

2017-06-30 17:30 UTC, brianlheim commented on grammars/supercollider.cson
> +    'match': '\\~[a-zA-Z0-9_]+'
Oh wow, actually `~ABC` isn't valid either! I learned something new today. So really,

`\\~[a-z][a-zA-Z0-9_]*`

2017-06-30 17:39 UTC, cechandler commented on grammars/supercollider.cson
> +    'match': '\\~[a-zA-Z0-9_]+'
Ah, great catches. This was a quick fix while I was working this morning, but this is more robust. I tested your solution, and it correctly does not highlight `~_`, `~_a`, `~ABC`, or `~900`.

Should I amend it and resubmit with `\\~[a-z][a-zA-Z0-9_]*`?

2017-06-30 18:27 UTC, brianlheim commented on grammars/supercollider.cson
> +    'match': '\\~[a-zA-Z0-9_]+'
Yes please, thank you!

2017-06-30 19:06 UTC, telephon approved these changes

2017-06-30 19:07 UTC, mossheim approved these changes
Thanks!

2017-06-30 19:07 UTC, merged

2017-07-03 09:29 UTC, crucialfelix commented
@brianlheim The atom release isn't that important because supercollider is the package that is mainly used (and I've merged the same changes in over there)

But to do that release you (or probably I) have to do `apm publish patch` which will create the `v.0.2.2` tag, push to github and push to atom's package repo all at once. So the tag you created here shouldn't have been done. 

But it's really not important. just FYI for future

thanks !

2017-07-03 13:55 UTC, brianlheim commented
thank you for the explanation @crucialfelix! The readme doesn't have any instructions for maintainers, so I thought it was as simple as creating a tag on GH. that would be a good process to document.

2017-07-03 14:34 UTC, brianlheim commented
@crucialfelix , would you like me to delete the release I made for cleanliness' sake?

2017-07-03 15:04 UTC, crucialfelix commented
I'll edit the readme

On Mon, Jul 3, 2017, 15:55 Brian Heim <notifications@github.com> wrote:

> thank you for the explanation @crucialfelix
> <https://github.com/crucialfelix>! The readme doesn't have any
> instructions for maintainers, so I thought it was as simple as creating a
> tag on GH. that would be a good process to document.
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/supercollider/language-supercollider/pull/3#issuecomment-312652139>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AANWcpHg8WXrOZ5kaJC8OuW5768Cp7fqks5sKPLrgaJpZM4OKpXA>
> .
>